In [7]:
import pandas as pd

In [8]:
df_raw = pd.read_excel('/home/chanwang1/CCC2024-BigDataAnalytics/data/raw/VIF2023_LGA_Pop_Age_Sex_Projections_to_2036.xlsx', sheet_name='ERP_by_Age_Persons')

In [9]:
df_raw

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 64,Unnamed: 65,Unnamed: 66,Unnamed: 67,Unnamed: 68,Unnamed: 69,Unnamed: 70,Unnamed: 71,Unnamed: 72,Unnamed: 73
0,Victoria in Future (VIF) population and househ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,September 2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Contact: David Sykes (DTP) david.sykes@delwp.v...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Estimated Resident Population (ERP) of all per...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85,27260,Wyndham (C),26850,27160,21490,16210,18660,23080,29630,33480,...,36270,34170,33820,23630,16940,13320,10500,8410,5950,5440
86,27350,Yarra (C),3760,3150,2900,2650,6950,14250,13280,8890,...,10970,9450,6920,5530,4930,4590,3870,3290,2390,2650
87,27450,Yarra Ranges (S),9620,9970,10170,9560,8870,9090,10580,10670,...,12420,12660,11530,9720,9810,9170,8580,8050,6510,6930
88,27630,Yarriambiack (S),290,320,410,340,250,280,320,290,...,360,360,290,250,280,380,460,490,350,390
89,29399,Unincorporated Vic,40,40,60,50,30,40,40,50,...,60,60,50,60,80,90,120,60,70,20

In [10]:
df = df_raw.iloc[8:]
df

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 64,Unnamed: 65,Unnamed: 66,Unnamed: 67,Unnamed: 68,Unnamed: 69,Unnamed: 70,Unnamed: 71,Unnamed: 72,Unnamed: 73
8,LGA code,LGA,Persons \n0-4,Persons \n5-9,Persons \n10-14,Persons \n15-19,Persons \n20-24,Persons \n25-29,Persons \n30-34,Persons \n35-39,...,Persons \n40-44,Persons \n45-49,Persons \n50-54,Persons \n55-59,Persons \n60-64,Persons \n65-69,Persons \n70-74,Persons \n75-79,Persons \n80-84,Persons \n85+
9,NaN,Victoria,386670,407990,398510,367500,420780,487520,510930,495550,...,603540,568420,518120,434630,412910,390850,351460,308180,238410,255600
10,20110,Alpine (S),540,680,800,650,610,650,620,710,...,930,890,920,910,990,950,930,910,650,650
11,20260,Ararat (RC),580,620,620,570,570,690,770,680,...,720,790,650,750,760,810,730,710,590,610
12,20570,Ballarat (C),6750,7350,7500,6940,7310,8190,7540,7270,...,9600,8960,8490,7850,7930,7700,7470,6790,5590,6120
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85,27260,Wyndham (C),26850,27160,21490,16210,18660,23080,29630,33480,...,36270,34170,33820,23630,16940,13320,10500,8410,5950,5440
86,27350,Yarra (C),3760,3150,2900,2650,6950,14250,13280,8890,...,10970,9450,6920,5530,4930,4590,3870,3290,2390,2650
87,27450,Yarra Ranges (S),9620,9970,10170,9560,8870,9090,10580,10670,...,12420,12660,11530,9720,9810,9170,8580,8050,6510,6930
88,27630,Yarriambiack (S),290,320,410,340,250,280,320,290,...,360,360,290,250,280,380,460,490,350,390
89,29399,Unincorporated Vic,40,40,60,50,30,40,40,50,...,60,60,50,60,80,90,120,60,70,20

In [11]:
df.columns=df.iloc[0]
df = df[1:]
df

8,LGA code,LGA,Persons \n0-4,Persons \n5-9,Persons \n10-14,Persons \n15-19,Persons \n20-24,Persons \n25-29,Persons \n30-34,Persons \n35-39,...,Persons \n40-44,Persons \n45-49,Persons \n50-54,Persons \n55-59,Persons \n60-64,Persons \n65-69,Persons \n70-74,Persons \n75-79,Persons \n80-84,Persons \n85+
9,NaN,Victoria,386670,407990,398510,367500,420780,487520,510930,495550,...,603540,568420,518120,434630,412910,390850,351460,308180,238410,255600
10,20110,Alpine (S),540,680,800,650,610,650,620,710,...,930,890,920,910,990,950,930,910,650,650
11,20260,Ararat (RC),580,620,620,570,570,690,770,680,...,720,790,650,750,760,810,730,710,590,610
12,20570,Ballarat (C),6750,7350,7500,6940,7310,8190,7540,7270,...,9600,8960,8490,7850,7930,7700,7470,6790,5590,6120
13,20660,Banyule (C),7250,7940,7710,6910,7190,7710,9010,9410,...,9710,10310,9870,9070,8510,7440,6620,6230,5030,5850
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85,27260,Wyndham (C),26850,27160,21490,16210,18660,23080,29630,33480,...,36270,34170,33820,23630,16940,13320,10500,8410,5950,5440
86,27350,Yarra (C),3760,3150,2900,2650,6950,14250,13280,8890,...,10970,9450,6920,5530,4930,4590,3870,3290,2390,2650
87,27450,Yarra Ranges (S),9620,9970,10170,9560,8870,9090,10580,10670,...,12420,12660,11530,9720,9810,9170,8580,8050,6510,6930
88,27630,Yarriambiack (S),290,320,410,340,250,280,320,290,...,360,360,290,250,280,380,460,490,350,390
89,29399,Unincorporated Vic,40,40,60,50,30,40,40,50,...,60,60,50,60,80,90,120,60,70,20

In [12]:
df['LGA'] = df['LGA'].str.replace(r'\(.*?\)', '', regex=True)

/tmp/ipykernel_9943/1045999329.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['LGA'] = df['LGA'].str.replace(r'\(.*?\)', '', regex=True)

In [13]:
df

8,LGA code,LGA,Persons \n0-4,Persons \n5-9,Persons \n10-14,Persons \n15-19,Persons \n20-24,Persons \n25-29,Persons \n30-34,Persons \n35-39,...,Persons \n40-44,Persons \n45-49,Persons \n50-54,Persons \n55-59,Persons \n60-64,Persons \n65-69,Persons \n70-74,Persons \n75-79,Persons \n80-84,Persons \n85+
9,NaN,Victoria,386670,407990,398510,367500,420780,487520,510930,495550,...,603540,568420,518120,434630,412910,390850,351460,308180,238410,255600
10,20110,Alpine,540,680,800,650,610,650,620,710,...,930,890,920,910,990,950,930,910,650,650
11,20260,Ararat,580,620,620,570,570,690,770,680,...,720,790,650,750,760,810,730,710,590,610
12,20570,Ballarat,6750,7350,7500,6940,7310,8190,7540,7270,...,9600,8960,8490,7850,7930,7700,7470,6790,5590,6120
13,20660,Banyule,7250,7940,7710,6910,7190,7710,9010,9410,...,9710,10310,9870,9070,8510,7440,6620,6230,5030,5850
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85,27260,Wyndham,26850,27160,21490,16210,18660,23080,29630,33480,...,36270,34170,33820,23630,16940,13320,10500,8410,5950,5440
86,27350,Yarra,3760,3150,2900,2650,6950,14250,13280,8890,...,10970,9450,6920,5530,4930,4590,3870,3290,2390,2650
87,27450,Yarra Ranges,9620,9970,10170,9560,8870,9090,10580,10670,...,12420,12660,11530,9720,9810,9170,8580,8050,6510,6930
88,27630,Yarriambiack,290,320,410,340,250,280,320,290,...,360,360,290,250,280,380,460,490,350,390
89,29399,Unincorporated Vic,40,40,60,50,30,40,40,50,...,60,60,50,60,80,90,120,60,70,20

In [14]:
df.columns

Index(['LGA  code', 'LGA', 'Persons \n0-4', 'Persons \n5-9', 'Persons \n10-14',
       'Persons \n15-19', 'Persons \n20-24', 'Persons \n25-29',
       'Persons \n30-34', 'Persons \n35-39', 'Persons \n40-44',
       'Persons \n45-49', 'Persons \n50-54', 'Persons \n55-59',
       'Persons \n60-64', 'Persons \n65-69', 'Persons \n70-74',
       'Persons \n75-79', 'Persons \n80-84', 'Persons \n85+', 'Persons \n0-4',
       'Persons \n5-9', 'Persons \n10-14', 'Persons \n15-19',
       'Persons \n20-24', 'Persons \n25-29', 'Persons \n30-34',
       'Persons \n35-39', 'Persons \n40-44', 'Persons \n45-49',
       'Persons \n50-54', 'Persons \n55-59', 'Persons \n60-64',
       'Persons \n65-69', 'Persons \n70-74', 'Persons \n75-79',
       'Persons \n80-84', 'Persons \n85+', 'Persons \n0-4', 'Persons \n5-9',
       'Persons \n10-14', 'Persons \n15-19', 'Persons \n20-24',
       'Persons \n25-29', 'Persons \n30-34', 'Persons \n35-39',
       'Persons \n40-44', 'Persons \n45-49', 'Persons \n50-54',
       'Persons \n55-59', 'Persons \n60-64', 'Persons \n65-69',
       'Persons \n70-74', 'Persons \n75-79', 'Persons \n80-84',
       'Persons \n85+', 'Persons \n0-4', 'Persons \n5-9', 'Persons \n10-14',
       'Persons \n15-19', 'Persons \n20-24', 'Persons \n25-29',
       'Persons \n30-34', 'Persons \n35-39', 'Persons \n40-44',
       'Persons \n45-49', 'Persons \n50-54', 'Persons \n55-59',
       'Persons \n60-64', 'Persons \n65-69', 'Persons \n70-74',
       'Persons \n75-79', 'Persons \n80-84', 'Persons \n85+'],
      dtype='object', name=8)

In [15]:
df.rename(columns={df.columns[2]: '2021Persons0-4',df.columns[3]: '2021Persons5-9',df.columns[4]: '2021Persons10-14',
                   df.columns[5]: '2021Persons15-19',df.columns[6]: '2021Persons20-24',df.columns[7]: '2021Persons25-29',
                   df.columns[8]: '2021Persons30-34',df.columns[9]: '2021Persons35-39',df.columns[10]: '2021Persons40-44',
                   df.columns[11]: '2021Persons45-49',df.columns[12]: '2021Persons50-54',df.columns[13]: '2021Persons55-59',
                   df.columns[14]: '2021Persons60-64',df.columns[15]: '2021Persons65-69',df.columns[16]: '2021Persons70-74',
                   df.columns[17]: '2021Persons75-79',df.columns[18]: '2021Persons80-84',df.columns[19]: '2021Persons85+',}, inplace=True)
df

/tmp/ipykernel_9943/3833808827.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={df.columns[2]: '2021Persons0-4',df.columns[3]: '2021Persons5-9',df.columns[4]: '2021Persons10-14',

8,LGA code,LGA,2021Persons0-4,2021Persons5-9,2021Persons10-14,2021Persons15-19,2021Persons20-24,2021Persons25-29,2021Persons30-34,2021Persons35-39,...,2021Persons40-44,2021Persons45-49,2021Persons50-54,2021Persons55-59,2021Persons60-64,2021Persons65-69,2021Persons70-74,2021Persons75-79,2021Persons80-84,2021Persons85+
9,NaN,Victoria,386670,407990,398510,367500,420780,487520,510930,495550,...,603540,568420,518120,434630,412910,390850,351460,308180,238410,255600
10,20110,Alpine,540,680,800,650,610,650,620,710,...,930,890,920,910,990,950,930,910,650,650
11,20260,Ararat,580,620,620,570,570,690,770,680,...,720,790,650,750,760,810,730,710,590,610
12,20570,Ballarat,6750,7350,7500,6940,7310,8190,7540,7270,...,9600,8960,8490,7850,7930,7700,7470,6790,5590,6120
13,20660,Banyule,7250,7940,7710,6910,7190,7710,9010,9410,...,9710,10310,9870,9070,8510,7440,6620,6230,5030,5850
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85,27260,Wyndham,26850,27160,21490,16210,18660,23080,29630,33480,...,36270,34170,33820,23630,16940,13320,10500,8410,5950,5440
86,27350,Yarra,3760,3150,2900,2650,6950,14250,13280,8890,...,10970,9450,6920,5530,4930,4590,3870,3290,2390,2650
87,27450,Yarra Ranges,9620,9970,10170,9560,8870,9090,10580,10670,...,12420,12660,11530,9720,9810,9170,8580,8050,6510,6930
88,27630,Yarriambiack,290,320,410,340,250,280,320,290,...,360,360,290,250,280,380,460,490,350,390
89,29399,Unincorporated Vic,40,40,60,50,30,40,40,50,...,60,60,50,60,80,90,120,60,70,20

In [24]:
df2021=df.iloc[:,0:20]

df2021['2021Persons_total']=df2021.iloc[:,2:20].sum(axis=1)

df2021=df2021.iloc[1:80,:]

df2021

df2021.to_json('/home/chanwang1/CCC2024-BigDataAnalytics/data/cleaned/population2021.json')

In [25]:
df2026=df.iloc[:,[0,1]+list(range(20,38))]
df2026['2026Persons_total']=df2026.iloc[:,2:20].sum(axis=1)

df2026

/tmp/ipykernel_9943/172556147.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2026['2026Persons_total']=df2026.iloc[:,2:20].sum(axis=1)

8,LGA code,LGA,2021Persons0-4,2021Persons5-9,2021Persons10-14,2021Persons15-19,2021Persons20-24,2021Persons25-29,2021Persons30-34,2021Persons35-39,...,2021Persons45-49,2021Persons50-54,2021Persons55-59,2021Persons60-64,2021Persons65-69,2021Persons70-74,2021Persons75-79,2021Persons80-84,2021Persons85+,2026Persons_total
9,NaN,Victoria,410490,406020,426230,448370,476500,530440,554470,547800,...,435340,419050,405800,378400,348490,297030,255920,168520,160380,7181630
10,20110,Alpine,580,610,730,730,500,720,720,710,...,820,900,910,1000,1090,900,760,480,400,13390
11,20260,Ararat,540,510,600,550,600,820,750,810,...,690,690,860,830,830,770,660,420,390,11920
12,20570,Ballarat,7070,7140,7800,8600,8330,7220,8550,8080,...,7140,7330,7000,6940,6780,6180,5330,3610,3420,124170
13,20660,Banyule,7030,7290,8190,8390,8290,7630,8410,9740,...,9040,8760,7870,7160,6860,5960,5490,3720,3630,133010
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85,27260,Wyndham,33650,29360,28510,23480,20360,26680,32040,33620,...,24290,17660,14450,12050,10020,7630,6000,3490,2750,360460
86,27350,Yarra,3960,2650,3070,4150,7310,15660,15080,12260,...,5780,5110,5150,4580,3880,3070,2880,1720,1430,105810
87,27450,Yarra Ranges,8860,10210,10370,10470,8900,9160,10460,11640,...,10050,10660,10350,9760,9060,7850,6990,4450,3360,163890
88,27630,Yarriambiack,290,310,320,320,250,310,320,360,...,280,320,390,500,590,460,400,290,280,6270
89,29399,Unincorporated Vic,40,40,60,40,40,30,50,50,...,70,50,70,110,70,110,50,20,10,960

In [26]:
df2026.rename(columns={df.columns[2]: '2026Persons0-4',df.columns[3]: '2026Persons5-9',df.columns[4]: '2026Persons10-14',
                   df.columns[5]: '2026Persons15-19',df.columns[6]: '2026Persons20-24',df.columns[7]: '2026Persons25-29',
                   df.columns[8]: '2026Persons30-34',df.columns[9]: '2026Persons35-39',df.columns[10]: '2026Persons40-44',
                   df.columns[11]: '2026Persons45-49',df.columns[12]: '2026Persons50-54',df.columns[13]: '2026Persons55-59',
                   df.columns[14]: '2026Persons60-64',df.columns[15]: '2026Persons65-69',df.columns[16]: '2026Persons70-74',
                   df.columns[17]: '2026Persons75-79',df.columns[18]: '2026Persons80-84',df.columns[19]: '2026Persons85+',}, inplace=True)

/tmp/ipykernel_9943/4154427847.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2026.rename(columns={df.columns[2]: '2026Persons0-4',df.columns[3]: '2026Persons5-9',df.columns[4]: '2026Persons10-14',

In [27]:
df2026=df2026.iloc[1:80,:]

df2026

8,LGA code,LGA,2026Persons0-4,2026Persons5-9,2026Persons10-14,2026Persons15-19,2026Persons20-24,2026Persons25-29,2026Persons30-34,2026Persons35-39,...,2026Persons45-49,2026Persons50-54,2026Persons55-59,2026Persons60-64,2026Persons65-69,2026Persons70-74,2026Persons75-79,2026Persons80-84,2026Persons85+,2026Persons_total
10,20110,Alpine,580,610,730,730,500,720,720,710,...,820,900,910,1000,1090,900,760,480,400,13390
11,20260,Ararat,540,510,600,550,600,820,750,810,...,690,690,860,830,830,770,660,420,390,11920
12,20570,Ballarat,7070,7140,7800,8600,8330,7220,8550,8080,...,7140,7330,7000,6940,6780,6180,5330,3610,3420,124170
13,20660,Banyule,7030,7290,8190,8390,8290,7630,8410,9740,...,9040,8760,7870,7160,6860,5960,5490,3720,3630,133010
14,20740,Bass Coast,1920,2030,2340,2300,1620,1800,1940,2110,...,2250,2640,3030,3560,4120,3720,3090,1980,1570,44300
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
84,27170,Wodonga,2920,2740,3070,3260,2960,2870,3110,3170,...,2580,2630,2680,2620,2380,2280,1890,1180,1070,46260
85,27260,Wyndham,33650,29360,28510,23480,20360,26680,32040,33620,...,24290,17660,14450,12050,10020,7630,6000,3490,2750,360460
86,27350,Yarra,3960,2650,3070,4150,7310,15660,15080,12260,...,5780,5110,5150,4580,3880,3070,2880,1720,1430,105810
87,27450,Yarra Ranges,8860,10210,10370,10470,8900,9160,10460,11640,...,10050,10660,10350,9760,9060,7850,6990,4450,3360,163890
88,27630,Yarriambiack,290,310,320,320,250,310,320,360,...,280,320,390,500,590,460,400,290,280,6270

In [28]:
df2026.to_json('/home/chanwang1/CCC2024-BigDataAnalytics/data/cleaned/population2026.json')