In [1]:
import pandas as pd
import geopandas as gpd
from shapely import wkt

In [2]:
gdf = gpd.read_file('LGA/LGA.shp')

In [3]:
gdf

,UFI,PFI,LGA_CODE,LGA_NAME,GAZ_LGA,GAZREGN,ABSLGACODE,TASK_ID,PFI_CR,UFI_OLD,UFI_CR,LABEL_USE_,geometry
0,820277766,356,356,nillumbik,NILLUMBIK SHIRE,G047 2003 p2972,25710,NaN,NaN,806916803,2023-12-19,4,"POLYGON ((2510304.792 2423656.532, 2510085.251..."
1,820277774,311,311,cardinia,CARDINIA SHIRE,G040 2003 p2572,21450,NaN,NaN,812373711,2023-12-19,2,"POLYGON ((2566196.702 2374717.795, 2566192.861..."
2,820277771,340,340,manningham,MANNINGHAM CITY,S158 1999 p10,24210,NaN,NaN,746966599,2023-12-19,5,"POLYGON ((2508276.751 2413515.594, 2508242.750..."
3,820277775,312,312,casey,CASEY CITY,S097 1994 p20,21610,NaN,NaN,806916808,2023-12-19,4,"POLYGON ((2536733.566 2364484.988, 2536709.616..."
4,821999870,377,377,yarra ranges,YARRA RANGES SHIRE,G040 2003 p2574,27450,NaN,NaN,820277769,2024-01-19,2,"POLYGON ((2570338.161 2408044.356, 2570380.255..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...
74,817074768,367,367,towong,TOWONG SHIRE,G042 1996 p2787,26670,NaN,NaN,582188524,2023-12-11,1,"POLYGON ((2694525.399 2565198.284, 2694510.597..."
75,820277772,342,342,maroondah,MAROONDAH CITY,S097 1994 p24,24410,NaN,NaN,767125154,2023-12-19,5,"POLYGON ((2527957.806 2408570.416, 2528057.165..."
76,820277768,355,355,murrindindi,MURRINDINDI SHIRE,G007 2012 p285,25620,NaN,NaN,814063080,2023-12-19,2,"MULTIPOLYGON (((2575080.282 2441049.421, 25748..."
77,820277765,382,382,mansfield,MANSFIELD SHIRE,G042 2002 p2839,24250,NaN,2003-01-29,808850949,2023-12-19,1,"POLYGON ((2586037.292 2470362.752, 2586030.009..."
78,820277770,305,305,baw baw,BAW BAW SHIRE,S094 1994 p9,20830,NaN,NaN,812373710,2023-12-19,1,"POLYGON ((2566992.271 2389671.271, 2566997.438..."

In [5]:
useful_geo=gdf[['ABSLGACODE','LGA_NAME','geometry']]
useful_geo

   ABSLGACODE      LGA_NAME                                           geometry
0       25710     nillumbik  POLYGON ((2510304.792 2423656.532, 2510085.251...
1       21450      cardinia  POLYGON ((2566196.702 2374717.795, 2566192.861...
2       24210    manningham  POLYGON ((2508276.751 2413515.594, 2508242.750...
3       21610         casey  POLYGON ((2536733.566 2364484.988, 2536709.616...
4       27450  yarra ranges  POLYGON ((2570338.161 2408044.356, 2570380.255...
..        ...           ...                                                ...
74      26670        towong  POLYGON ((2694525.399 2565198.284, 2694510.597...
75      24410     maroondah  POLYGON ((2527957.806 2408570.416, 2528057.165...
76      25620   murrindindi  MULTIPOLYGON (((2575080.282 2441049.421, 25748...
77      24250     mansfield  POLYGON ((2586037.292 2470362.752, 2586030.009...
78      20830       baw baw  POLYGON ((2566992.271 2389671.271, 2566997.438...

[79 rows x 3 columns]

In [6]:
useful_geo.to_file('/home/chanwang1/CCC2024-BigDataAnalytics/data/cleaned/LGA_useful_geo/useful.shp')

In [11]:
useful_geo.to_file('/home/chanwang1/CCC2024-BigDataAnalytics/data/cleaned/useful_geo.geojson', driver='GeoJSON')